language: node_js
node_js:
    - "6"
    - "8"
install:
    - npm install -g yarn
    - npm install -g codecov
    - yarn
script:
    - npm run test
    - istanbul cover ./node_modules/mocha/bin/_mocha --reporter lcovonly -- --recursive test -R spec
    - codecov
